# Generated by Django 2.0.2 on 2018-03-30 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_num_of_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', related_query_name='tag', to='questions.Question'),
            preserve_default=False,
        ),
    ]
