# Generated by Django 2.0.2 on 2018-04-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_tag_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
