# Generated by Django 2.0.2 on 2018-05-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='questions.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
