# Generated by Django 2.0.2 on 2018-05-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20180507_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
    ]
