# Generated by Django 2.0.2 on 2018-05-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20180508_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tags', related_query_name='tag', to='questions.Question'),
            preserve_default=False,
        ),
    ]
