# Generated by Django 2.0.2 on 2018-05-08 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0017_auto_20180508_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(related_name='questions', related_query_name='question', to='questions.Question')),
                ('user', models.ManyToManyField(related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
