# Generated by Django 2.0.2 on 2018-05-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20180514_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_of_ans',
        ),
    ]
