# Generated by Django 2.0.2 on 2018-05-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_remove_question_num_of_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
